/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintRouteImport } from './routes/print'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAcoesRouteImport } from './routes/admin/acoes'
import { Route as AcaoIdRouteImport } from './routes/acao.$id'

const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcoesRoute = AdminAcoesRouteImport.update({
  id: '/admin/acoes',
  path: '/admin/acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AcaoIdRoute = AcaoIdRouteImport.update({
  id: '/acao/$id',
  path: '/acao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/print': typeof PrintRoute
  '/acao/$id': typeof AcaoIdRoute
  '/admin/acoes': typeof AdminAcoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/print': typeof PrintRoute
  '/acao/$id': typeof AcaoIdRoute
  '/admin/acoes': typeof AdminAcoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/print': typeof PrintRoute
  '/acao/$id': typeof AcaoIdRoute
  '/admin/acoes': typeof AdminAcoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/print' | '/acao/$id' | '/admin/acoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/print' | '/acao/$id' | '/admin/acoes'
  id: '__root__' | '/' | '/print' | '/acao/$id' | '/admin/acoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrintRoute: typeof PrintRoute
  AcaoIdRoute: typeof AcaoIdRoute
  AdminAcoesRoute: typeof AdminAcoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/acoes': {
      id: '/admin/acoes'
      path: '/admin/acoes'
      fullPath: '/admin/acoes'
      preLoaderRoute: typeof AdminAcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acao/$id': {
      id: '/acao/$id'
      path: '/acao/$id'
      fullPath: '/acao/$id'
      preLoaderRoute: typeof AcaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrintRoute: PrintRoute,
  AcaoIdRoute: AcaoIdRoute,
  AdminAcoesRoute: AdminAcoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
